---
kind: pipeline
type: ssh
name: Build Hestia for RHEL AMD64

platform:
  os: linux
  arch: amd64
  
server:
  host:
    from_secret: server_address
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
  - name: Cleanup SOURCES & SPECS folder
    commands:
    - rm -rf /home/hestia/rpmbuild/SPECS/* /home/hestia/rpmbuild/SOURCES/* /home/hestia/rpmbuild/SRPMS/* /home/hestia/hestiacp
  - name: Clone HestiaCP
    commands:
    - cd /home/hestia/ && git clone https://github.com/hestiacp/hestiacp
  - name: Get SPECS & SOURCES
    environment:
      VERSION: 1.23.4
    commands:
    - cp /home/hestia/hestiacp/src/rpm/nginx/nginx.conf /home/hestia/rpmbuild/SOURCES/nginx.conf
    - cp /home/hestia/hestiacp/src/rpm/nginx/hestia-nginx.spec /home/hestia/rpmbuild/SPECS/hestia-nginx.spec
    - cp /home/hestia/hestiacp/src/rpm/nginx/hestia-nginx.service /home/hestia/rpmbuild/SOURCES/hestia-nginx.service
    - wget https://nginx.org/download/nginx-1.23.4.tar.gz -P /home/hestia/rpmbuild/SOURCES/
  - name: Build source RPMS
    commands:
    - rpmbuild -bs /home/hestia/rpmbuild/SPECS/hestia-nginx.spec
  - name: RHEL 8
    environment:
      VERSION: 1.23.4
      HOME: /home/hestia
    commands:
    - mkdir -p /home/hestia/packages/rhel8/
    - mock -r rocky+epel-8-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-nginx-$VERSION-1.el9.src.rpm
    - cp /var/lib/mock/rocky+epel-8-$(arch)/result/*.rpm /home/hestia/packages/rhel8/
  - name: RHEL 9
    environment:
      VERSION: 1.23.4
      HOME: /home/hestia
    commands:
    - mkdir -p /home/hestia/packages/rhel9/
    - mock -r rocky+epel-9-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-nginx-$VERSION-1.el9.src.rpm
    - cp /var/lib/mock/rocky+epel-9-$(arch)/result/*.rpm /home/hestia/packages/rhel9/
  - name: scp files
    commands:
    - echo "To do create tar file and scp"
    
trigger:
  event: [ promote ]
    
---
  kind: pipeline
  type: ssh
  name: Push
  
  platform:
    os: linux
    arch: amd64
    
  server:
    host:
      from_secret: server_address
    user:
      from_secret: username
    ssh_key:
      from_secret: ssh_key
      
  steps:
  - name: Test
    commands:
    - echo "Hestia"