---
kind: pipeline
type: docker
name: Build Hestia for AMD64

platform:
  os: linux
  arch: amd64

steps:
  - name: Redhat 8
    image: rockylinux:8 
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./install_rpm.sh
    - ./hestiacp/src/hst_autocompile.sh --dontinstalldeps --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/rhel8/
    - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel8/
    - rm -rf /tmp/hestia-src/
  - name: Redhat 9
    image: rockylinux:9 
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./install_rpm.sh
    - ./hestiacp/src/hst_autocompile.sh --dontinstalldeps --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/rhel9/
    - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel9/
    - rm -rf /tmp/hestia-src/
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: target_server
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
        - ./packages/*
        
trigger:
  event: [ push ]

---
kind: pipeline
type: docker
name: Build Hestia for ARM64

platform:
  os: linux
  arch: arm64

steps:
  - name: Redhat 8
    image: rockylinux:8 
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./install_rpm.sh
    - ./hestiacp/src/hst_autocompile.sh --dontinstalldeps --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/rhel8/
    - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel8/
    - rm -rf /tmp/hestia-src/
  - name: Redhat 9
    image: rockylinux:9 
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./install_rpm.sh
    - ./hestiacp/src/hst_autocompile.sh --dontinstalldeps --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/rhel9/
    - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel9/
    - rm -rf /tmp/hestia-src/
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: target_server
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
        - ./packages/*
        
trigger:
  event: [ push ]
