---
kind: pipeline
type: docker
name: Build Hestia for AMD64

platform:
  os: linux
  arch: amd64

steps:
  - name: Clone HestiaCP
    image: alpine/git
    commands:
      - git clone https://github.com/hestiacp/hestiacp.git
      - cd hestiacp
      - git checkout ${branch}
  - name: Build JS/CSS
    image: node:current-slim
    commands:
    - cd ./hestiacp/
    - yarn set version stable
    - yarn install
    - yarn build
  - name: Ubuntu 22.04
    image: ubuntu:jammy
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./build_packages.sh
    - mkdir -p ./packages/jammy
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/jammy
    - rm -rf /tmp/hestia-src/
  - name: Ubuntu 20.04
    image: ubuntu:focal
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./build_packages.sh
    - mkdir -p ./packages/focal
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/focal
    - rm -rf /tmp/hestia-src/
  - name: Ubuntu 18.04
    image: ubuntu:bionic
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./build_packages.sh
    - mkdir -p ./packages/bionic
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/bionic
    - rm -rf /tmp/hestia-src/
  - name: Debian 10
    image: debian:buster
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./build_packages.sh
    - mkdir -p ./packages/buster
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/buster
    - rm -rf /tmp/hestia-src/
  - name: Debian 11
    image: debian:bullseye
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./build_packages.sh
    - mkdir -p ./packages/bullseye
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/bullseye
    - rm -rf /tmp/hestia-src/
  - name: RHEL 8
    image: rockylinux:8 
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./build_packages.sh
    - mkdir -p ./packages/rhel8/
    - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel8/
    - rm -rf /tmp/hestia-src/
  - name: RHEL 9
    image: rockylinux:9 
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./build_packages.sh
    - mkdir -p ./packages/rhel9/
    - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel9/
    - rm -rf /tmp/hestia-src/
  - name: scp files
    image: appleboy/drone-scp:1.6.4
    settings:
      host:
        from_secret: target_server
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
      - ./packages/*
    
trigger:
  event: [ promote ]
  
---
  kind: pipeline
  type: docker
  name: Build Hestia for ARM64
  
  platform:
    os: linux
    arch: arm64
  
  steps:
    - name: Clone HestiaCP
      image: alpine/git
      commands:
        - git clone https://github.com/hestiacp/hestiacp.git
        - cd hestiacp
        - git checkout ${branch}
    - name: Build JS/CSS
      image: node:current-slim
      commands:
      - cd ./hestiacp/
      - yarn set version stable
      - yarn install
      - yarn build
    - name: Ubuntu 22.04
      image: ubuntu:jammy
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./build_packages.sh
      - mkdir -p ./packages/jammy
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/jammy
      - rm -rf /tmp/hestia-src/
    - name: Ubuntu 20.04
      image: ubuntu:focal
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./build_packages.sh
      - mkdir -p ./packages/focal
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/focal
      - rm -rf /tmp/hestia-src/
    - name: Ubuntu 18.04
      image: ubuntu:bionic
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./build_packages.sh
      - mkdir -p ./packages/bionic
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/bionic
      - rm -rf /tmp/hestia-src/
    - name: Debian 10
      image: debian:buster
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./build_packages.sh
      - mkdir -p ./packages/buster
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/buster
      - rm -rf /tmp/hestia-src/
    - name: Debian 11
      image: debian:bullseye
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./build_packages.sh
      - mkdir -p ./packages/bullseye
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/bullseye
      - rm -rf /tmp/hestia-src/
    - name: RHEL 8
      image: rockylinux:8 
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./build_packages.sh
      - mkdir -p ./packages/rhel8/
      - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel8/
      - rm -rf /tmp/hestia-src/
    - name: RHEL 9
      image: rockylinux:9 
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./build_packages.sh
      - mkdir -p ./packages/rhel9/
      - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel9/
      - rm -rf /tmp/hestia-src/
    - name: scp files
      image: appleboy/drone-scp:1.6.4
      settings:
        host:
          from_secret: target_server
        user: root
        key:
          from_secret: ssh_key
        port: 22
        command_timeout: 2m
        target: /root/
        source:
        - ./packages/*
      
  trigger:
    event: [ promote ]
    
---
  kind: pipeline
  type: docker
  name: Push
  
  platform:
    os: linux
    arch: amd64
  
  steps:
    - name: Check
      image: alpine/git
      commands:
        - git clone https://github.com/hestiacp/hestiacp.git
        - cd hestiacp
  trigger:
  event: [ push ]