---
kind: pipeline
type: docker
name: Build Hestia for AMD64

platform:
  os: linux
  arch: amd64

steps:
  - name: Clone HestiaCP
    image: alpine/git
    commands:
      - git clone https://github.com/hestiacp/hestiacp.git
      - cd hestiacp
      - echo "Checkout ${branch}"
      - git checkout ${branch}
  - name: Ubuntu 24.04
    image: ubuntu:noble
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/jammy
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/jammy
    - rm -rf /tmp/hestia-src/
  - name: Ubuntu 22.04
    image: ubuntu:jammy
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/jammy
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/jammy
    - rm -rf /tmp/hestia-src/
  - name: Ubuntu 20.04
    image: ubuntu:focal
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/focal
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/focal
    - rm -rf /tmp/hestia-src/
  - name: Debian 10
    image: debian:buster
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/buster
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/buster
    - rm -rf /tmp/hestia-src/
  - name: Debian 11
    image: debian:bullseye
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/bullseye
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/bullseye
    - rm -rf /tmp/hestia-src/
  - name: Debian 12
    image: debian:bookworm
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/bookworm
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/bookworm
    - rm -rf /tmp/hestia-src/
  - name: scp files
    image: appleboy/drone-scp:1.6.4
    settings:
      host:
        from_secret: target_server
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
      - ./packages/*
    
trigger:
  event: [ promote ]
  
---
  kind: pipeline
  type: docker
  name: Build Hestia for ARM64
  
  platform:
    os: linux
    arch: arm64
  
  steps:
    - name: Clone HestiaCP
      image: alpine/git
      commands:
        - git clone https://github.com/hestiacp/hestiacp.git
        - cd hestiacp
        - echo "Checkout ${branch}"
        - git checkout ${branch}
    - name: Build JS/CSS
      image: node:current-slim
      commands:
      - cd ./hestiacp/
      - npm ci
      - npm run build
    - name: Ubuntu 24.04
      image: ubuntu:noble
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
      - mkdir -p ./packages/jammy
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/jammy
      - rm -rf /tmp/hestia-src/
    - name: Ubuntu 22.04
      image: ubuntu:jammy
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
      - mkdir -p ./packages/jammy
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/jammy
      - rm -rf /tmp/hestia-src/
    - name: Ubuntu 20.04
      image: ubuntu:focal
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
      - mkdir -p ./packages/focal
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/focal
      - rm -rf /tmp/hestia-src/
    - name: Debian 10
      image: debian:buster
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
      - mkdir -p ./packages/buster
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/buster
      - rm -rf /tmp/hestia-src/
    - name: Debian 11
      image: debian:bullseye
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
      - mkdir -p ./packages/bullseye
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/bullseye
      - rm -rf /tmp/hestia-src/
    - name: Debian 12
      image: debian:bookworm
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
      - mkdir -p ./packages/bookworm
      - mv /tmp/hestiacp-src/deb/*.deb ./packages/bookworm
      - rm -rf /tmp/hestia-src/
    - name: scp files
      image: appleboy/drone-scp:1.6.4
      settings:
        host:
          from_secret: target_server
        user: root
        key:
          from_secret: ssh_key
        port: 22
        command_timeout: 2m
        target: /root/
        source:
        - ./packages/*
      
  trigger:
    event: [ promote ]
    
---
  kind: pipeline
  type: docker
  name: Push
  
  platform:
    os: linux
    arch: amd64
  
  steps:
    - name: Check
      image: alpine/git
      commands:
        - git clone https://github.com/hestiacp/hestiacp.git
        - cd hestiacp
  trigger:
  event: [ push ]
