---
kind: pipeline
type: docker
name: Build Hestia for AMD64

platform:
  os: linux
  arch: amd64

steps:
  - name: Clone HestiaCP
    image: alpine/git
    commands:
      - git clone https://github.com/hestiacp/hestiacp.git
      - cd hestiacp
      - echo "Checkout ${branch}"
      - git checkout ${branch}
  - name: Build JS/CSS
    image: node:current-slim
    commands:
    - cd ./hestiacp/
    - yarn set version stable
    - yarn install
    - yarn build
  - name: RHEL 9
    image: rockylinux:9 
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/rhel9/
    - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel9/
    - rm -rf /tmp/hestia-src/
  - name: scp files
    image: appleboy/drone-scp:1.6.4
    settings:
      host:
        from_secret: target_server
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
      - ./packages/*
    
trigger:
  event: [ promote ]
  
---
  kind: pipeline
  type: docker
  name: Build Hestia for ARM64
  
  platform:
    os: linux
    arch: arm64
  
  steps:
    - name: Clone HestiaCP
      image: alpine/git
      commands:
        - git clone https://github.com/hestiacp/hestiacp.git
        - cd hestiacp
        - echo "Checkout ${branch}"
        - git checkout ${branch}
    - name: Build JS/CSS
      image: node:current-slim
      commands:
      - cd ./hestiacp/
      - yarn set version stable
      - yarn install
      - yarn build
    - name: RHEL 9
      image: rockylinux:9 
      commands:
      - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
      - ./hestiacp/src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
      - mkdir -p ./packages/rhel9/
      - mv /tmp/hestiacp-src/rpm/*.rpm ./packages/rhel9/
      - rm -rf /tmp/hestia-src/
    - name: scp files
      image: appleboy/drone-scp:1.6.4
      settings:
        host:
          from_secret: target_server
        user: root
        key:
          from_secret: ssh_key
        port: 22
        command_timeout: 2m
        target: /root/
        source:
        - ./packages/*
      
  trigger:
    event: [ promote ]
    
---
  kind: pipeline
  type: docker
  name: Push
  
  platform:
    os: linux
    arch: amd64
  
  steps:
    - name: Check
      image: alpine/git
      commands:
        - git clone https://github.com/hestiacp/hestiacp.git
        - cd hestiacp
  trigger:
  event: [ push ]