---
kind: pipeline
type: ssh
name: Build Hestia for RHEL AMD64

platform:
  os: linux
  arch: amd64
  
server:
  host:
    from_secret: server_address
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
  - name: Cleanup SOURCES & SPECS folder
    commands:
    - rm -rf /home/hestia/rpmbuild/SPECS/* /home/hestia/rpmbuild/SOURCES/* /home/hestia/rpmbuild/SRPMS/* /home/hestia/hestiacp
  - name: Clone HestiaCP
    commands:
    - cd /home/hestia/ && git clone https://github.com/istiak101/hestiacp && cd /home/hestia/hestiacp && git checkout rhel-build-system
  - name: Get SPECS & SOURCES
    environment:
      NGINX: 1.24.0
      PHP: 8.2.6
      HESTIA: 1.8.0~alpha
    commands:
    - cp /home/hestia/hestiacp/src/rpm/nginx/nginx.conf /home/hestia/rpmbuild/SOURCES/nginx.conf
    - cp /home/hestia/hestiacp/src/rpm/nginx/hestia-nginx.spec /home/hestia/rpmbuild/SPECS/hestia-nginx.spec
    - cp /home/hestia/hestiacp/src/rpm/nginx/hestia-nginx.service /home/hestia/rpmbuild/SOURCES/hestia-nginx.service
    - wget -q https://nginx.org/download/nginx-$NGINX.tar.gz -P /home/hestia/rpmbuild/SOURCES/
    - cp /home/hestia/hestiacp/src/rpm/php/php-fpm.conf /home/hestia/rpmbuild/SOURCES/php-fpm.conf
    - cp /home/hestia/hestiacp/src/rpm/php/php.ini /home/hestia/rpmbuild/SOURCES/php.ini
    - cp /home/hestia/hestiacp/src/rpm/php/hestia-php.spec /home/hestia/rpmbuild/SPECS/hestia-php.spec
    - cp /home/hestia/hestiacp/src/rpm/php/hestia-php.service /home/hestia/rpmbuild/SOURCES/hestia-php.service
    - wget -q http://de2.php.net/distributions/php-$PHP.tar.gz -P /home/hestia/rpmbuild/SOURCES/
    - cp /home/hestia/hestiacp/src/rpm/hestia/hestia.spec /home/hestia/rpmbuild/SPECS/hestia.spec
    - cp /home/hestia/hestiacp/src/rpm/hestia/hestia.service /home/hestia/rpmbuild/SOURCES/hestia.service
    - tar -czf /home/hestia/rpmbuild/SOURCES/hestia-$HESTIA.tar.gz -C /home/hestia hestiacp
  - name: Build source RPMS
    environment:
      HOME: /home/hestia
    commands:
    - rpmbuild -bs /home/hestia/rpmbuild/SPECS/hestia-nginx.spec
    - rpmbuild -bs /home/hestia/rpmbuild/SPECS/hestia-php.spec
    - rpmbuild -bs /home/hestia/rpmbuild/SPECS/hestia.spec
  - name: RHEL 9
    environment:
      NGINX: 1.24.0
      PHP: 8.2.6
      HESTIA: 1.8.0~alpha
    commands:
    - mkdir -p /home/hestia/packages/rhel9/
    - mock -r rocky+epel-9-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-nginx-$NGINX-1.el9.src.rpm
    - cp -f /var/lib/mock/rocky+epel-9-$(arch)/result/*.rpm /home/hestia/packages/rhel9/
    - mock -r rocky+epel-9-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-php-$PHP-1.el9.src.rpm
    - cp -f /var/lib/mock/rocky+epel-9-$(arch)/result/*.rpm /home/hestia/packages/rhel9/
    - mock -r rocky+epel-9-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-$HESTIA-1.el9.src.rpm
    - cp -f /var/lib/mock/rocky+epel-9-$(arch)/result/*.rpm /home/hestia/packages/rhel9/
  - name: RHEL 8
    environment:
      NGINX: 1.24.0
      PHP: 8.2.6
      HESTIA: 1.8.0~alpha
    commands:
    - mkdir -p /home/hestia/packages/rhel8/
    - mock -r rocky+epel-8-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-nginx-$NGINX-1.el9.src.rpm
    - cp -f /var/lib/mock/rocky+epel-8-$(arch)/result/*.rpm /home/hestia/packages/rhel8/
    - mock -r rocky+epel-8-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-php-$PHP-1.el9.src.rpm
    - cp -f /var/lib/mock/rocky+epel-8-$(arch)/result/*.rpm /home/hestia/packages/rhel8/
    - mock -r rocky+epel-8-$(arch) rebuild /home/hestia/rpmbuild/SRPMS/hestia-$HESTIA-1.el9.src.rpm
    - cp -f /var/lib/mock/rocky+epel-8-$(arch)/result/*.rpm /home/hestia/packages/rhel8/
  - name: scp files
    commands:
    - echo "To do create tar file and scp"
    
trigger:
  event: [ promote ]
    
---
  kind: pipeline
  type: ssh
  name: Push
  
  platform:
    os: linux
    arch: amd64
    
  server:
    host:
      from_secret: server_address
    user:
      from_secret: username
    ssh_key:
      from_secret: ssh_key
      
  steps:
  - name: Test
    commands:
    - echo "Hestia"