---
kind: pipeline
type: ssh
name: Build Hestia for RHEL AMD64

platform:
  os: linux
  arch: amd64
  
server:
  host:
    from_secret: server_address
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
  - name: Cleanup SOURCES & SPECS folder
    commands:
    - rm -rf ~/rpmbuild/SPECS/* ~/rpmbuild/SOURCES/* ~/rpmbuild/SRPMS/* ~/hestiacp
  - name: Clone HestiaCP
    commands:
    - cd ~ && git clone https://github.com/hestiacp/hestiacp
  - name: Get SPECS & SOURCES
    commands:
    - cp /home/hestiacp/hestiacp/src/rpm/nginx/nginx.conf /home/hestiacp/rpmbuild/SOURCES/nginx.conf
    - cp /home/hestiacp/hestiacp/src/rpm/nginx/hestia-nginx.spec /home/hestiacp/rpmbuild/SPECS/hestia-nginx.spec
    - cp /home/hestiacp/hestiacp/src/rpm/nginx/hestia-nginx.service /home/hestiacp/rpmbuild/SOURCES/hestia-nginx.service
    - wget https://nginx.org/download/nginx-1.24.0.tar.gz /home/hestiacp/rpmbuild/SOURCES/
  - name: Build source RPMS
    commands:
    - rpmbuild -bs ~/rpmbuild/SPECS/hestia-nginx.spec
  - name: RHEL 8
    commands:
    - mkdir -p ./packages/rhel8/
    - mock -r rocky+epel-8-$(arch) ~/rpmbuild/SRPMS/hestia-nginx-1.24.0-1.el8.src.rpm
    - cp /var/lib/mock/rocky+epel-8-$(arch)/result/*.rpm ./packages/rhel8/
  - name: RHEL 9
    commands:
    - mkdir -p ./packages/rhel9/
    - mock -r rocky+epel-9-$(arch) ~/rpmbuild/SRPMS/hestia-nginx-1.24.0-1.el9.src.rpm
    - cp /var/lib/mock/rocky+epel-9-$(arch)/result/*.rpm ./packages/rhel9/
  - name: scp files
    commands:
    - echo "To do create tar file and scp"
    
trigger:
  event: [ promote ]
    
---
  kind: pipeline
  type: ssh
  name: Push
  
  platform:
    os: linux
    arch: amd64
    
  server:
    host:
      from_secret: server_address
    user:
      from_secret: username
    ssh_key:
      from_secret: ssh_key
      
  steps:
  - name: Test
    commands:
    - echo "Hestia"